all:

#####################################################################################################################################################################################
# build .dot and .pdf files of arithmetic orations

	build/mavlc -dot syntax -o src/ownTests/testcases/trees/P1/arithmetic/_01/arithmetic_addSub1.xml src/ownTests/testcases/trees/P1/arithmetic/_01/arithmetic_addSub1.mavl
	dot -Tpdf -o src/ownTests/testcases/trees/P1/arithmetic/_01/arithmetic_addSub1.pdf src/ownTests/testcases/trees/P1/arithmetic/_01/arithmetic_addSub1_ast.dot

	build/mavlc -dot syntax -o src/ownTests/testcases/trees/P1/arithmetic/_02/arithmetic_compare1.xml src/ownTests/testcases/trees/P1/arithmetic/_02/arithmetic_compare1.mavl
	dot -Tpdf -o src/ownTests/testcases/trees/P1/arithmetic/_02/arithmetic_compare1.pdf src/ownTests/testcases/trees/P1/arithmetic/_02/arithmetic_compare1_ast.dot

	build/mavlc -dot syntax -o src/ownTests/testcases/trees/P1/arithmetic/_02/arithmetic_compare2.xml src/ownTests/testcases/trees/P1/arithmetic/_02/arithmetic_compare2.mavl
	dot -Tpdf -o src/ownTests/testcases/trees/P1/arithmetic/_02/arithmetic_compare2.pdf src/ownTests/testcases/trees/P1/arithmetic/_02/arithmetic_compare2_ast.dot

	build/mavlc -dot syntax -o src/ownTests/testcases/trees/P1/arithmetic/_03/arithmetic_exponentation1.xml src/ownTests/testcases/trees/P1/arithmetic/_03/arithmetic_exponentation1.mavl
	dot -Tpdf -o src/ownTests/testcases/trees/P1/arithmetic/_03/arithmetic_exponentation1.pdf src/ownTests/testcases/trees/P1/arithmetic/_03/arithmetic_exponentation1_ast.dot

	build/mavlc -dot syntax -o src/ownTests/testcases/trees/P1/arithmetic/_04/arithmetic_mulDiv.xml src/ownTests/testcases/trees/P1/arithmetic/_04/arithmetic_mulDiv.mavl
	dot -Tpdf -o src/ownTests/testcases/trees/P1/arithmetic/_04/arithmetic_mulDiv.pdf src/ownTests/testcases/trees/P1/arithmetic/_04/arithmetic_mulDiv_ast.dot

	build/mavlc -dot syntax -o src/ownTests/testcases/trees/P1/arithmetic/_05/arithmetic_not.xml src/ownTests/testcases/trees/P1/arithmetic/_05/arithmetic_not.mavl
	dot -Tpdf -o src/ownTests/testcases/trees/P1/arithmetic/_05/arithmetic_not.pdf src/ownTests/testcases/trees/P1/arithmetic/_05/arithmetic_not_ast.dot

	build/mavlc -dot syntax -o src/ownTests/testcases/trees/P1/arithmetic/_06/arithmetic_unaryMinus.xml src/ownTests/testcases/trees/P1/arithmetic/_06/arithmetic_unaryMinus.mavl
	dot -Tpdf -o src/ownTests/testcases/trees/P1/arithmetic/_06/arithmetic_unaryMinus.pdf src/ownTests/testcases/trees/P1/arithmetic/_06/arithmetic_unaryMinus_ast.dot

#####################################################################################################################################################################################
# build .dot and .pdf files of loops

	build/mavlc -dot syntax -o src/ownTests/testcases/trees/P1/loop/_01/loop_forEach.xml src/ownTests/testcases/trees/P1/loop/_01/loop_forEach.mavl
	dot -Tpdf -o src/ownTests/testcases/trees/P1/loop/_01/loop_forEach.pdf src/ownTests/testcases/trees/P1/loop/_01/loop_forEach_ast.dot

	build/mavlc -dot syntax -o src/ownTests/testcases/trees/P1/loop/_02/loop_iteratorDecl.xml src/ownTests/testcases/trees/P1/loop/_02/loop_iteratorDecl.mavl
	dot -Tpdf -o src/ownTests/testcases/trees/P1/loop/_02/loop_iteratorDecl.pdf src/ownTests/testcases/trees/P1/loop/_02/loop_iteratorDecl_ast.dot

#####################################################################################################################################################################################
# build .dot and .pdf files of records

	build/mavlc -dot syntax -o src/ownTests/testcases/trees/P1/records/_01/records_elementDecl.xml src/ownTests/testcases/trees/P1/records/_01/records_elementDecl.mavl
	dot -Tpdf -o src/ownTests/testcases/trees/P1/records/_01/records_elementDecl.pdf src/ownTests/testcases/trees/P1/records/_01/records_elementDecl_ast.dot

	build/mavlc -dot syntax -o src/ownTests/testcases/trees/P1/records/_02/records_elementSelect.xml src/ownTests/testcases/trees/P1/records/_02/records_elementSelect.mavl
	dot -Tpdf -o src/ownTests/testcases/trees/P1/records/_02/records_elementSelect.pdf src/ownTests/testcases/trees/P1/records/_02/records_elementSelect_ast.dot

	build/mavlc -dot syntax -o src/ownTests/testcases/trees/P1/records/_03/records_typeDecl.xml src/ownTests/testcases/trees/P1/records/_03/records_typeDecl.mavl
	dot -Tpdf -o src/ownTests/testcases/trees/P1/records/_03/records_typeDecl.pdf src/ownTests/testcases/trees/P1/records/_03/records_typeDecl_ast.dot

#####################################################################################################################################################################################
# build .dot and .pdf files of switch

	build/mavlc -dot syntax -o src/ownTests/testcases/trees/P1/switch/_01/switch01.xml src/ownTests/testcases/trees/P1/switch/_01/switch01.mavl
	dot -Tpdf -o src/ownTests/testcases/trees/P1/switch/_01/switch01.pdf src/ownTests/testcases/trees/P1/switch/_01/switch01_ast.dot

	build/mavlc -dot syntax -o src/ownTests/testcases/trees/P1/switch/_02/switch02.xml src/ownTests/testcases/trees/P1/switch/_02/switch02.mavl
	dot -Tpdf -o src/ownTests/testcases/trees/P1/switch/_02/switch02.pdf src/ownTests/testcases/trees/P1/switch/_02/switch02_ast.dot

	build/mavlc -dot syntax -o src/ownTests/testcases/trees/P1/switch/_03/switch03.xml src/ownTests/testcases/trees/P1/switch/_03/switch03.mavl
	dot -Tpdf -o src/ownTests/testcases/trees/P1/switch/_03/switch03.pdf src/ownTests/testcases/trees/P1/switch/_03/switch03_ast.dot

	build/mavlc -dot syntax -o src/ownTests/testcases/trees/P1/switch/_04/switch04.xml src/ownTests/testcases/trees/P1/switch/_04/switch04.mavl
	dot -Tpdf -o src/ownTests/testcases/trees/P1/switch/_04/switch04.pdf src/ownTests/testcases/trees/P1/switch/_04/switch04_ast.dot

	build/mavlc -dot syntax -o src/ownTests/testcases/trees/P1/switch/_05/switch05.xml src/ownTests/testcases/trees/P1/switch/_05/switch05.mavl
	dot -Tpdf -o src/ownTests/testcases/trees/P1/switch/_05/switch05.pdf src/ownTests/testcases/trees/P1/switch/_05/switch05_ast.dot

#####################################################################################################################################################################################
# build .dot and .pdf files of ternary operation

	build/mavlc -dot syntax -o src/ownTests/testcases/trees/P1/ternary/_01/ternary01.xml src/ownTests/testcases/trees/P1/ternary/_01/ternary01.mavl
	dot -Tpdf -o src/ownTests/testcases/trees/P1/ternary/_01/ternary01.pdf src/ownTests/testcases/trees/P1/ternary/_01/ternary01_ast.dot

	build/mavlc -dot syntax -o src/ownTests/testcases/trees/P1/ternary/_02/ternary02.xml src/ownTests/testcases/trees/P1/ternary/_02/ternary02.mavl
	dot -Tpdf -o src/ownTests/testcases/trees/P1/ternary/_02/ternary02.pdf src/ownTests/testcases/trees/P1/ternary/_02/ternary02_ast.dot

#####################################################################################################################################################################################
# build .dot and .pdf files of variables and values

	build/mavlc -dot syntax -o src/ownTests/testcases/trees/P1/varVal/_01/assign01.xml src/ownTests/testcases/trees/P1/varVal/_01/assign01.mavl
	dot -Tpdf -o src/ownTests/testcases/trees/P1/varVal/_01/assign01.pdf src/ownTests/testcases/trees/P1/varVal/_01/assign01_ast.dot

	build/mavlc -dot syntax -o src/ownTests/testcases/trees/P1/VarVal/_02/valueDecl01.xml src/ownTests/testcases/trees/P1/VarVal/_02/valueDecl01.mavl
	dot -Tpdf -o src/ownTests/testcases/trees/P1/VarVal/_02/valueDecl01.pdf src/ownTests/testcases/trees/P1/VarVal/_02/valueDecl01_ast.dot

	build/mavlc -dot syntax -o src/ownTests/testcases/trees/P1/VarVal/_03/valueDef01.xml src/ownTests/testcases/trees/P1/VarVal/_03/valueDef01.mavl
	dot -Tpdf -o src/ownTests/testcases/trees/P1/VarVal/_03/valueDef01.pdf src/ownTests/testcases/trees/P1/VarVal/_03/valueDef01_ast.dot
	
